### ISSUE TITLE
[Improvement] Choice: Improve documentation on `disabled`

### ISSUE THREAD

**Issue by monicawheeler** [Kajabi/sage-lib#1002]
## Description

Currently, using a `div` does not allow for the `disabled` prop to work. This is not documented and can cause confusion for developers. 

https://sage-design-system.kajabi.com/pages/component/choice -> See **Properties** tab

## Improvement

Add more documentation around the property `disabled` to either indicate where it's valid or where it is not valid.

## Additional Information

[Slack request](https://kajabi.slack.com/archives/G01F8KE3WKD/p1635893484050800)

**Comment by monicawheeler** [comment]
Consider `aria` disabled

**Comment by philschanely** [comment]
Moved to Jira https://kajabi.atlassian.net/browse/UXD-94
