### ISSUE TITLE
[Improvement] Table caption alignment properties

### ISSUE THREAD

**Issue by monkeypox8** [Kajabi/sage-lib#1008]
## Description
The Sage Table currently allows use of `caption` for an overall description, but our CSS reboot defaults `caption` placement to the bottom of each table.

Providing the option to align the `caption` content (using `caption-side`) will unlock flexibility for table layouts while nudging developers to use proper semantics.

## Additional Information
- https://developer.mozilla.org/en-US/docs/Web/CSS/caption-side
- https://www.w3.org/WAI/tutorials/tables/caption-summary/

**Comment by philschanely** [comment]
In Jira for record keeping in cycle https://kajabi.atlassian.net/browse/UXD-82
