### ISSUE TITLE
[Improvement] Implement a responsive solution for `grid_template`s

### ISSUE THREAD

**Issue by QuintonJason** [Kajabi/sage-lib#1009]
## Description

Currently most of our row list content contains a `...` menu to the right. When everything stacks vertically on mobile, that button is last in the row which is not ideal. We'll need to elevate the `...` menu with design feedback. Issue present wherever `grid_template` is used

## Additional Information

![Screen Shot 2021-11-09 at 7 21 05 PM](https://user-images.githubusercontent.com/1241836/141032355-76e44132-5ce2-4e89-a6cd-c4efb08dee49.png)

**Comment by monkeypox8** [comment]
Moved to Jira: https://kajabi.atlassian.net/browse/UXD-83
