### ISSUE TITLE
[Button] revisit subtle button interaction

### ISSUE THREAD

**Issue by QuintonJason** [Kajabi/sage-lib#1011]
Non-blocking item: the focus state for `subtle` buttons feels a little choppy. I'm wondering if we can cut the `after` transition's `transform` timing to say, `0.1s`. As it currently stands, my guess is the `0.2s` duration is too long for the relative transform, drawing out the transition's appearance. I tried to add a screen capture, but the limited frame rate doesn't seem to show the effect the same way.

_Originally posted by @monkeypox8 in https://github.com/Kajabi/sage-lib/pull/967#discussion_r745022352_

**Comment by monkeypox8** [comment]
Moved to Jira: https://kajabi.atlassian.net/browse/SAGE-108
