### ISSUE TITLE
[Improvement] Add `gap` to sage tokens

### ISSUE THREAD

**Issue by QuintonJason** [Kajabi/sage-lib#1015]
### Rails 
- Add the `gap` prop to the tokens similar to `spacers` in rails and react
- Create Rails `gap` in the schema
- Rails update `gap` props in `.rb` files to use schema instead of `string` of `set`

### React
- Create `gap` token / classname
- Move `GAP_OPTIONS` config items and calls to use the tokenized version

**Comment by monicawheeler** [comment]
FYI - may be helpful to work in-flight on: https://github.com/Kajabi/sage-lib/pull/1032

**Comment by philschanely** [comment]
Moved to Jira https://kajabi.atlassian.net/browse/UXD-93
