### ISSUE TITLE
[Improvement] Doc Site: Remove Generated HTML Code section

### ISSUE THREAD

**Issue by monicawheeler** [Kajabi/sage-lib#1024]
## Description

In an effort to remove unnecessary documentation, remove the "Generated HTML Code" section from the doc site. 

## Additional Information

![Screen Shot 2021-11-11 at 4 03 09 PM](https://user-images.githubusercontent.com/24237393/141375367-6d541580-3b29-48aa-933c-caf1bdb4e171.png)

**Comment by philschanely** [comment]
https://kajabi.atlassian.net/browse/UXD-55
