### ISSUE TITLE
[Improvement] Doc site: Remove Attribute Schema section

### ISSUE THREAD

**Issue by monicawheeler** [Kajabi/sage-lib#1025]
## Description

- [ ] Remove "Attribute Schema" from the Code tab

## Additional Information
![Screen Shot 2021-11-11 at 4 04 50 PM](https://user-images.githubusercontent.com/24237393/141375512-4a16da57-ab1e-4621-bb99-d1c330e110e9.png)

**Comment by monkeypox8** [comment]
Moved to Jira: https://kajabi.atlassian.net/browse/UXD-70
