### ISSUE TITLE
[Improvement] Buttons: Evaluate the `value` property

### ISSUE THREAD

**Issue by monicawheeler** [Kajabi/sage-lib#1031]
## Description

Currently, the button's `value` property is noted as `optional`. This property should be on every type of button. 

![Screen Shot 2021-11-16 at 12 13 23 PM](https://user-images.githubusercontent.com/24237393/142042035-4a5a6d8a-ae5b-4bfc-bb07-f4a62c884a6b.png)

## Design
N/A

**Comment by monkeypox8** [comment]
Moved to Jira: https://kajabi.atlassian.net/browse/UXD-87
