### ISSUE TITLE
[Improvement] Docs: Add Color tokens to colors page

### ISSUE THREAD

**Issue by philschanely** [Kajabi/sage-lib#1041]
## Description

Colors page currently shows the scss token functions but the latest Rails and React tokens are probably more useful. Add the following for each color:

- [ ] Classname tokens (outputs `t-sage--color-X`)
   - Rails: `SageClassnames::TYPE_COLORS::X` (SAGE, SAGE_100, SAGE_200, etc.)
   - React: `SageClassnames.TYPE_COLORS.X`
- [ ] Hex token (outputs `#xxxxxx`)
   - Rails: `SageTokens::COLOR_PALETTE::X` (SAGE, SAGE_100, SAGE_200, etc.)
   - React: `SageTokens.COLOR_PALETTE.X`

**Comment by anechol** [comment]
Hey @philschanely I've begun work on this, but I'm wondering what format we're expecting for the new content here. Should we keep the current setup now and add a new section with this information underneath what we currently have? Or are we refactoring the format now to replace the scss colors with the new content?
