### ISSUE TITLE
[Improvement] Pagination: make window an optional param

### ISSUE THREAD

**Issue by QuintonJason** [Kajabi/sage-lib#1057]
## Description

Pagination is based on the [Kaminari Repo](https://github.com/kaminari/kaminari)

Document what the `window` is regarding `SagePagination`. When `window` is omitted from the `SagePagination` call, the following error is shown:

![Screen Shot 2021-11-30 at 11 02 51 AM](https://user-images.githubusercontent.com/1241836/144111904-baf9aee5-53ec-4665-9829-0ef8ba0c4dce.png)

**Comment by philschanely** [comment]
Moved to Jira https://kajabi.atlassian.net/browse/UXD-56
