### ISSUE TITLE
[BUG] update-release workflow: not triggering

### ISSUE THREAD

**Issue by monicawheeler** [Kajabi/sage-lib#1062]
## Detailed description

Investigate the cause of the [update-release workflow](https://github.com/Kajabi/sage-lib/actions/workflows/update-release.yml) not triggering.

## Steps to reproduce
View [Actions](https://github.com/Kajabi/sage-lib/actions/workflows/update-release.yml) and [code](https://github.com/Kajabi/sage-lib/blob/develop/.github/workflows/update-release.yml)

**Comment by philschanely** [comment]
Moved to Jira
