### ISSUE TITLE
[Improvement] Doc site: tabs in component view add slug

### ISSUE THREAD

**Issue by monicawheeler** [Kajabi/sage-lib#1064]
## Description

In the Rails doc site, add a slug to the URL to indicate what tab we are viewing. This can make for easier navigation and linking.

### Currently
![Screen Shot 2021-12-01 at 4 28 13 PM](https://user-images.githubusercontent.com/24237393/144324429-6379fe71-6c91-4d9a-abd8-e3af39ffee26.png)

### Desired
![Screen Shot 2021-12-01 at 4 29 30 PM](https://user-images.githubusercontent.com/24237393/144324567-233c2e53-8195-4363-842b-09971983473c.png)

**Comment by philschanely** [comment]
Moved to Jira https://kajabi.atlassian.net/browse/UXD-78
