### ISSUE TITLE
[BUG] Build failures in Github

### ISSUE THREAD

**Issue by monkeypox8** [Kajabi/sage-lib#1067]
## Detailed description
Builds are failing due to a Node version mismatch from a [recent Github upgrade (v14 -> v16)](https://github.com/actions/node-versions/releases).

## Steps to reproduce
1. View any current pull request in the repo
2. Scroll to the build/checks section, and click the "Details" button of the "Lint, test, build" action
3. Confirm that the build displays an error (example below)

## Screenshots
![build-failure](https://user-images.githubusercontent.com/816579/144523097-d5e63644-8ad2-4fe5-868c-92da2bb1a0cc.png)

**Comment by monicawheeler** [comment]
Builds no longer failing. Issue resolved via #1068
