### ISSUE TITLE
[Improvement] Input Group - Repurpose or Deprecation

### ISSUE THREAD

**Issue by anechol** [Kajabi/sage-lib#1072]
## Description

As mentioned in #196, we should consider repurposing or completely deprecating the Input Group component. This will require a bigger effort than the Input Helper considering there are instances of the Input Group in use within Kajabi Products.

**Comment by philschanely** [comment]
@anechol do I recall some work on this had been started somewhere?

**Comment by anechol** [comment]
@philschanely Work on this hasn't begun just yet.

**Comment by philschanely** [comment]
Moved to Jira https://kajabi.atlassian.net/browse/UXD-90
