### ISSUE TITLE
[Improvement] Standardize props of all React components

### ISSUE THREAD

**Issue by monkeypox8** [Kajabi/sage-lib#1074]
## Description
Currently, our React components define their properties individually (`active`, `icon`, etc). Many of these properties and attributes are understandably unique to each component. However, a default configuration for common properties would be highly beneficial for a consistent developer experience. This will also help React components maintain parity with their Rails counterparts, which include a [standardized property set](https://github.com/Kajabi/sage-lib/blob/develop/docs/lib/sage_rails/app/sage_components/sage_component.rb) of their own.

### Suggestion
Create one, or several, sets of configs to import in each component.

**Base set**
- `id`
- `className`
- `testId`

Similar components can then add on with their own sets:
**Form input set**
- `disabled`
- `hasError`
- `name`

**Image set**
- `icon`, `size`, etc.

**Comment by philschanely** [comment]
Moved to Jira https://kajabi.atlassian.net/browse/UXD-79
