### ISSUE TITLE
[BUG] Script: `yarn branches:update` script fails incorrectly

### ISSUE THREAD

**Issue by monicawheeler** [Kajabi/sage-lib#1076]
## Detailed description

While running `yarn branches:update`, the conditionals written in `bin/branches.sh` can exit incorrectly. 

## Suggested resolution
* Show the detail of the git request 
* Only exit the conditional in the `sh` file when an error occurs

## Workaround for now
Run the manual git commands during the version bump:
1. `git checkout main`
2. `git pull`
3. `git checkout develop`
4. `git pull`
5. `git rebase main`
6. `git push -f`

## Steps to reproduce
Describe the steps to reproduce the behavior: 
1. Run` yarn branches:update` 
2. Observe the git process and if it exits too early, even if successful

<img width="748" alt="Screen Shot 2021-12-05 at 3 35 37 PM" src="https://user-images.githubusercontent.com/24237393/144764770-6e774d28-048d-4e92-a183-f97d0cd8a960.png">

**Comment by anechol** [comment]
This issue seems to occur if you're already checked out on either the `main` or `develop` branch. Running this command on a branch other than those two has just worked fine for me.

**Comment by monkeypox8** [comment]
Moved to Jira: https://kajabi.atlassian.net/browse/SAGE-116
