### ISSUE TITLE
[BUG] Unable to easily test with Switch

### ISSUE THREAD

**Issue by philschanely** [Kajabi/sage-lib#1097]
## Detailed description

Testing in Capybara with Switch appears to be harder than expected to trigger interactions. An engineer found that switching the z-index made the component more testable. See Slack thread: https://kajabi.slack.com/archives/C01A424HY8Y/p1639493691004700

Engineers expect to be able to select the Switch (assuming by id or `test_id`) and instruct capybara to click it to activate/toggle it. This does not appear to function out of the gate.

Engineer has manual z-index workaround but a more permanent fix is needed from Sage.

## Steps to reproduce

Steps recorded by Engineer:

- I used a Sage Switch react component. Works fine clicking around in the browser
then i needed to write a capybara spec for it, and it said the input was being intercepted by the label (so the selenium chrome driver thing couldn’t click on the switch)
- i tried having it click on the label but it says that’s not an interactive element
- i inspected element on the switch in the UI and it does appear to select the label, not the input
- i changed the z-index to 100 on the component and now when i inspect it, the input is selected and the capybara spec works great

**Comment by sdhull** [comment]
FWIW an old dev friend of mine used to swear by having labels that _contained_ their inputs. Limits styling options in some cases, but might be a good option here! 📝

**Comment by philschanely** [comment]
Thanks, @sdhull . I've seen both used (and done so myself too). Interesting to note that while [MDN suggests](https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_structure_a_web_form#:~:text=Even%20in%20such%20cases%20however%2C%20it%20is%20considered%20best%20practice%20to%20set%20the%20for%20attribute%20to%20ensure%20all%20assistive%20technologies%20understand%20the%20relationship%20between%20label%20and%20widget.) wrapping is feasible, [this author says](https://css-tricks.com/html-inputs-and-labels-a-love-story/#:~:text=name%22%20name%3D%22name%22%20/%3E-,Unfortunately%2C%20an%20implicit%20label%20is%20not%20handled%20correctly%20by%20all%20assistive%20technologies%2C%20even%20if%20for%20and%20id%20attributes%20are%20used.%20Therefore%2C%20it%20is%20always%20the%20best%20idea%20to%20use%20an%20explicit%20label%20instead%20of%20an%20implicit%20label.) there may be issues with wrapping the label around inputs in some assistive technologies.

**Comment by philschanely** [comment]
Moved to Jira https://kajabi.atlassian.net/browse/UXD-86
