### ISSUE TITLE
[Improvement] add dragOptions to the SageSortable component

### ISSUE THREAD

**Issue by QuintonJason** [Kajabi/sage-lib#1101]
## Description

- [x] Add a `dragClass` to the options located in the [React Sortable repo](https://github.com/SortableJS/Sortable#options)
This change should be added to [`dragClass`](https://github.com/Kajabi/sage-lib/blob/develop/packages/sage-react/lib/Sortable/Sortable.jsx#L23) before the `{...rest}`

**Comment by AndrwM** [comment]
**Note ->** When we close this issue we want to remove this shim here:
https://github.com/Kajabi/kajabi-products/blob/main/app/javascript/apps/quizzes/QuizBuilder/components/QuestionsEditor/QuestionsEditor.jsx#L36-L37
