### ISSUE TITLE
[Suggestion] DISCOVERY: Convert Sage components to web components

### ISSUE THREAD

**Issue by monicawheeler** [Kajabi/sage-lib#1104]
## Description

Determine scope of converting components to web components.

- [ ] - What is the process to convert a component?
- [ ] - How long will it take?
- [ ] - Do we need to write custom JS for all functionality? 

- Will they truly work in Rails without headache?
- Will React lifecycles have expected impact on them?
- What is the development experience like for our team?
- What do we make about backwards compatibility if IE 11 does not support them?
- What about exiting Rails-oriented aspects such as simple form, etc

**Comment by anechol** [comment]
I love this idea!

**Comment by philschanely** [comment]
Moved to Jira https://kajabi.atlassian.net/browse/UXD-34
