### ISSUE TITLE
[Improvement] Alerts: Add dismissable and button option for small Alert

### ISSUE THREAD

**Issue by monicawheeler** [Kajabi/sage-lib#1105]
## Description

Design update to alert; add a dismiss button and an action item for small variation of the alert

## Design
[Design file for alerts](https://www.figma.com/file/9Km09NjlZHYWsMP7EGT8tI/?node-id=6989%3A21570)

## Additional Information
![Screen Shot 2021-12-15 at 2 12 47 PM](https://user-images.githubusercontent.com/24237393/146258260-61386635-f264-4162-a423-bf882fc083bb.png)

**Comment by monkeypox8** [comment]
Moved to Jira: https://kajabi.atlassian.net/browse/SAGE-117
