### ISSUE TITLE
[BUG] SageDropdown menu hidden when near the bottom of the screen

### ISSUE THREAD

**Issue by kajabimark** [Kajabi/sage-lib#1114]
## Detailed description
When using a `SageDropdown` near the bottom of the screen, the menu is hidden by the browser and scrolling is disabled

Maybe the menu could show above the button by default when there isn't enough room, or just allow users to scroll to reveal the menu content.

## Steps to reproduce
1. Visit the [SageDropdown docs page](https://sage-design-system.kajabi.com/pages/component/dropdown)
2. Open one of the`SageDropdown` components near the bottom of the screen (or shrink the browser window so the Dropdown is near the bottom)

## Screenshots
![image](https://user-images.githubusercontent.com/86270449/146424357-6d4d8f59-dab5-4013-9a31-7fd9350f96fe.png)

**Comment by monkeypox8** [comment]
Moved to Jira: https://kajabi.atlassian.net/browse/SAGE-114
