### ISSUE TITLE
[Improvement] Page Heading wrapping needs improvement

### ISSUE THREAD

**Issue by QuintonJason** [Kajabi/sage-lib#1139]
## Description

- [ ] When text doesn't contain spaces, it does not wrap
- [ ] Text wrapping is breaking the action button alignment

## Design

![Screen Shot 2022-01-10 at 10 55 15 AM](https://user-images.githubusercontent.com/1241836/148806639-2d8f11b8-d25a-4e2c-add4-74d280f403fe.png)

#### No space no wrap

![Screen Shot 2022-01-10 at 10 54 58 AM](https://user-images.githubusercontent.com/1241836/148806525-c0943b5e-e1b7-4a86-90ee-23e66f59a965.png)

#### action button alignment
![Screen Shot 2022-01-10 at 10 54 20 AM](https://user-images.githubusercontent.com/1241836/148806544-3445be8b-05c6-4bae-a3dc-2d885557004d.png)

**Comment by monkeypox8** [comment]
Moved to Jira: https://kajabi.atlassian.net/browse/UXD-81
