### ISSUE TITLE
[Mock]: Product Selection

### ISSUE THREAD

**Issue by pixelflips** [Kajabi/sage-lib#1147]
[Figma](https://www.figma.com/file/aYygNca9JqBoQs1VwwFyRd/Product-Creation-Flow?node-id=2740%3A15652)

![Screen Shot 2021-12-13 at 4 38 52 PM](https://user-images.githubusercontent.com/17955295/145893001-ca7103d5-6d18-4591-900c-53b168dc88e4.png)

**Comment by philschanely** [comment]
Now in Jira https://github.com/Kajabi/sage-lib/issues/1147
