### ISSUE TITLE
[BUG] Modal - Margins are stacking and not sitting adjacently

### ISSUE THREAD

**Issue by QuintonJason** [Kajabi/sage-lib#1152]
## Detailed description

> Describe in detail the issue you're having.
In modals the margins are collapsing with the `display` fallback back to `block` for `<div>`s. This is causing the need to overwrite with zeros whenever the parent of collapsed margins contains `display: flex;`.

> Is this issue related to a specific component?
Sage Modal

> What did you expect to happen? What happened instead? What would you like to see changed?
`margin-top`s and `margin-bottom`s should always affect the element it's tied to and not overlap or collapse one

> What browser are you working in?
All

## Steps to reproduce
Describe the steps to reproduce the behavior: 
1. Visit the [Modal rails page](http://localhost:4000/pages/component/modal)
2. Inspect the `sage-modal__header`, `sage-modal__content`, and `sage-modal__footer` to verify that their margins are adjacent and not stacked on top each other 

## Screenshots
Provide screenshots, videos, or gifs of issue.
![stackingmargins](https://user-images.githubusercontent.com/1241836/149365188-5a5066c5-e579-41ca-9a09-5b789392a0d6.gif)

**Comment by monkeypox8** [comment]
Moved to Jira: https://kajabi.atlassian.net/browse/SAGE-113
