### ISSUE TITLE
[Mock] Product dropdown

### ISSUE THREAD

**Issue by pixelflips** [Kajabi/sage-lib#1154]
Figma: [Initial state](https://www.figma.com/file/UfJlrF5IZTlKTstbKCaith/COMM-1494-Offer-Creation-Flow?node-id=1513%3A5471) | [Selections added](https://www.figma.com/file/UfJlrF5IZTlKTstbKCaith/COMM-1494-Offer-Creation-Flow?node-id=1587%3A4558) | [Menu](https://www.figma.com/file/UfJlrF5IZTlKTstbKCaith/COMM-1494-Offer-Creation-Flow?node-id=1549%3A4373)

![Screen Shot 2021-12-13 at 4 43 36 PM](https://user-images.githubusercontent.com/17955295/145893624-9fec09fb-acce-416e-913d-b5e988e7df2a.png)

**Comment by philschanely** [comment]
Moved to Jira https://kajabi.atlassian.net/browse/UXD-45
