### ISSUE TITLE
[Improvement] React Storybook Dropdown - Descriptions & Sample Code

### ISSUE THREAD

**Issue by kajabimark** [Kajabi/sage-lib#1356]
## Description

In the Sage storybook, can we:
- Add `prop` descriptions to all custom props
- Include possible values for our custom props
- Include code samples

Often the description is blank or something non-descriptive like `node` or `func`, but including more detail about possible values that the prop accepts or what the function is used for will really help. For example,  the [Dropdown](https://sage-lib-storybook.herokuapp.com/?path=/docs/sage-dropdown--default) component's `triggerModifier` and `panelModifier` props  take a string, but updating that value on the storybook seems to have no change. A short description of what this prop is used for and what values it accepts would be very helpful.

Can we also include samples of each component in the `show code` section? For example, one of the items under the `<Dropdown />` component is "Menu with custom panel" but the sample code just shows `<CustomPanelStory />` so there's no way to know what the component is named or how to create a Dropdown with a custom panel.

**Comment by philschanely** [comment]
Thanks so much for this request, @kajabimark ! We will make a consolidated effort to improve these docs as soon as we can. I have created this Jira issue to track: https://kajabi.atlassian.net/browse/SAGE-461

I'll close this issue so as to use the Jira issue instead.
