### ISSUE TITLE
Create a basic Sage show/hide component (Rails)

### ISSUE THREAD

**Issue by monkeypox8** [Kajabi/sage-lib#166]
## Description
Controls throughout our app use third-party solutions to selectively show and hide associated content. This is most frequently seen within forms where optional fields are hidden away until needed.

While React components do not share this problem, [Twine's](https://shopify.github.io/twine/) `bind-show` and Bootstrap's [Collapse](https://getbootstrap.com/docs/3.3/javascript/#collapse) are or will be deprecated with the move to Sage, and we should replace these with a generic component that allows improved functionality.

## Related

- n/a

**Comment by philschanely** [comment]
Moved to Jira https://kajabi.atlassian.net/browse/UXD-64
