### ISSUE TITLE
[BUG] in react <Modal />, setting disableBackgroundDismiss to true has the effect of also setting disableBackgroundBlur to true 

### ISSUE THREAD

**Issue by duhrich** [Kajabi/sage-lib#1702]
## Detailed description

> Describe in detail the issue you're having.

Background blur is unexpectedly disabled when disabling background dismiss in the react modal component

> Is this issue related to a specific component?

This is related to the react `<Modal />` component

> What did you expect to happen? What happened instead? What would you like to see changed?

Expect the background to stay blurred when `disableBackgroundDismiss` is true (unless `disableBackgroundBlur` is also explicitly set)

> What browser are you working in?

Tested in Chrome, Safari and Mobile Safari

## Steps to reproduce
Describe the steps to reproduce the behavior: 
1. Create and open a <Modal />, set `disableBackgroundDismiss=false`
2. Observe background is blurred
3. Set `disableBackgroundDismiss=true`, observer background is NOT blurred, become sad

## Screenshots
In this clip, `disableBackgroundDismiss` is set when the pay button is clicked to prevent user from navigating away from in progress payment. This works as expected, but the background blur disappears at the same time 😢 

![modal blur issue](https://user-images.githubusercontent.com/1461692/223185828-7cadf698-60ad-4bae-afb2-a922f1ce3b06.gif)

**Comment by monicawheeler** [comment]
@duhrich - hi there! I created a ticket for this internally in Jira. I've added you there and closed this issue. Thanks for the report!
