### ISSUE TITLE
DESIGN: Icon Font Update

### ISSUE THREAD

**Issue by samcroswell** [Kajabi/sage-lib#219]
<img width="1195" alt="Screen Shot 2021-01-15 at 10 24 07 AM" src="https://user-images.githubusercontent.com/74267385/104764156-d6897c00-571b-11eb-9f1c-fd2853e7cb52.png">

### This update includes:
**New and redesigned icons:**
- file
- draft
- duplicate 
- rename 
- location

**Fixes for icons that didn't have a rounded edge:**
- closed-captions 
- add-image 
- flag 
- danger

ZIP file available here: 
: https://www.dropbox.com/s/eci3jq18yd4twbp/icomoon-v1.4.zip?dl=0

**Comment by philschanely** [comment]
Relates to #182

**Comment by samcroswell** [comment]
@joedakroub updated zip: https://www.dropbox.com/s/eci3jq18yd4twbp/icomoon-v1.4.zip?dl=0

I noticed in the icomoon preview there was a few icons with some strange svg path errors going on. Not sure if they were just an icomoon bug or if they really are like that. Let me know if these icons are not rendering properly when implemented:

<img width="237" alt="Screen Shot 2021-01-20 at 9 29 40 AM" src="https://user-images.githubusercontent.com/74267385/105212286-1d071e00-5b02-11eb-8f2c-50bffc14444e.png">
<img width="196" alt="Screen Shot 2021-01-20 at 9 29 35 AM" src="https://user-images.githubusercontent.com/74267385/105212290-1d9fb480-5b02-11eb-9b7d-3de65ef2f42a.png">
<img width="193" alt="Screen Shot 2021-01-20 at 9 29 30 AM" src="https://user-images.githubusercontent.com/74267385/105212292-1d9fb480-5b02-11eb-9b61-f8814664790d.png">
<img width="235" alt="Screen Shot 2021-01-20 at 9 29 25 AM" src="https://user-images.githubusercontent.com/74267385/105212293-1e384b00-5b02-11eb-9efc-9fc31f684e3e.png">
<img width="137" alt="Screen Shot 2021-01-20 at 9 29 22 AM" src="https://user-images.githubusercontent.com/74267385/105212297-1e384b00-5b02-11eb-9a1d-b7ce569ac3f0.png">
<img width="161" alt="Screen Shot 2021-01-20 at 9 29 14 AM" src="https://user-images.githubusercontent.com/74267385/105212300-1ed0e180-5b02-11eb-8a54-669b26f06643.png">
<img width="155" alt="Screen Shot 2021-01-20 at 9 29 02 AM" src="https://user-images.githubusercontent.com/74267385/105212301-1ed0e180-5b02-11eb-81b4-33d41262860d.png">

**Comment by joedakroub** [comment]
@samcroswell Confirmed that these icons do have rendering problems. 

I am seeing proper rendering locally, but other UXDs are seeing the same issues you mention above. 

We can try to re-export again, but the local `demo.html` file should reveal these issues before we move them to Sage.

**Comment by monicawheeler** [comment]
Closing this issue as the icons requested to be added and the corners are rounded on the icons that were updated. Also, confirmed that the icons with display issues as noted in the comments are rendering properly 👍 - this task is no longer needed.
