### ISSUE TITLE
Expandable Card

### ISSUE THREAD

**Issue by QuintonJason** [Kajabi/sage-lib#242]

**Comment by QuintonJason** [comment]
- [x] - created rails component #240

**Comment by philschanely** [comment]
- [ ] Design spec is being added in Figma and the component needs to be synced to it.
- [ ] Needs to be added in React as well.

**Comment by philschanely** [comment]
- [ ] Design is investigated variations to this component. @samcroswell 
- [ ] UXD will need to build once settled.
