### ISSUE TITLE
Tooltip on Dropdown items

### ISSUE THREAD

**Issue by philschanely** [Kajabi/sage-lib#328]
## Description

- [ ] Look into whether or not Tooltips are supported on Dropdown items and add this ability if necessary.
- [ ] Ensure that disabled items allow this.
- [ ] Ensure both Rails and React components add support in similar fashion.

Related Component: #228

**Comment by sdhull** [comment]
Additional request:
- [ ] Ensure that disabled buttons & links can have tooltips and/or popovers

We sometimes want to include a "More info" type of link in these

**Comment by philschanely** [comment]
@pixelflips is this indeed closable?
