### ISSUE TITLE
Deprecate Input Helper component

### ISSUE THREAD

**Issue by monkeypox8** [Kajabi/sage-lib#333]
## Description
The Sage Input Helper was intended for use in a feature that was partially implemented, but ultimately shelved. We can safely remove this component and its references within the Input Group as there is no (known) future use.

<img src="https://user-images.githubusercontent.com/816579/108786870-73181880-7529-11eb-9bc7-971728588366.png" width="360">

**Comment by monicawheeler** [comment]
Duplicate Issue: https://github.com/Kajabi/sage-lib/issues/196
