### ISSUE TITLE
Standardize base properties for all components

### ISSUE THREAD

**Issue by monkeypox8** [Kajabi/sage-lib#338]
## Description
Ideally we should have a standardized set of properties that can be expected across all components regardless of size or scope, including:
- `id`
- `css_classes`
- `data` attributes

While many of the larger components have the ability to specify these attributes, their child elements do not always provide for this ability without the additional overlap of the `html_attributes` hash.

Allowing for `class` and `data` attributes would seem to be the highest priority of the three, particularly so that `data-kjb-element` attributes can be used for specs and QE tests. Rolling out `id` throughout could present problems with uniqueness once components are used at scale.

h/t @mostfamiliar

**Comment by monkeypox8** [comment]
CSS clases addressed in #443

**Comment by philschanely** [comment]
MOved to Jira https://kajabi.atlassian.net/browse/UXD-79
