### ISSUE TITLE
sage-sortable spacing

### ISSUE THREAD

**Issue by cmcfadzean** [Kajabi/sage-lib#441]
Padding needs to be removed from sage-sortable

<img width="683" alt="Screen Shot 2021-04-28 at 10 11 12 AM" src="https://user-images.githubusercontent.com/14350772/116445098-54c0e880-a80a-11eb-96c5-8d967001e300.png">

**Comment by philschanely** [comment]
@cmcfadzean could you please clarify where you found this issue?

**Comment by philschanely** [comment]
Note to dev: Evaluate whether this is a Sage matter or on the `kp` side.

**Comment by philschanely** [comment]
Moved to Jira https://kajabi.atlassian.net/browse/UXD-89
