### ISSUE TITLE
Update Interactive states

### ISSUE THREAD

**Issue by philschanely** [Kajabi/sage-lib#491]
## Description

(Possibly in partnership with [Form field L1](https://github.com/Kajabi/sage-lib/issues/496))

Consider a mixin or similar approach to implement new focus styles consistently. Investigate how current focus is set up and build a new approach in a non-destructive/backwards-compliant way that can be implemented as each component is updated in follow-up tickets.

Also consider whether other common interactivity such as `:hover` and "active" (selected state, not `:active`).

**Comment by QuintonJason** [comment]
Per conversation with design, we'll need to remove the `box-shadow` from the `<button>`s default state. It will also required the raised attribute to be removed. May handle that portion in a followup PR to reduce the effect of the breaking change.
<img width="829" alt="Screen_Shot_2021-06-03_at_8_18_24_AM" src="https://user-images.githubusercontent.com/1241836/120651676-a6314880-c444-11eb-99f3-f3b1e2cf9d32.png">

**Comment by QuintonJason** [comment]
This issue stems from the fact that the focus ring and `box-shadow` will exist in the interactive element, not a wrapper or container. We have two options to handle currently:
1. add an inner `<span>` or `<div>` for the sole purpose of one of the box-shadow
2. remove the `box-shadow` from interactive elements that have a `raised` state
We're choosing option 2 for now

**Comment by FuturaExtraBold** [comment]
Closing this, as the Button updates branch has been merged.
