### ISSUE TITLE
SimpleForm in Sage

### ISSUE THREAD

**Issue by philschanely** [Kajabi/sage-lib#492]
## Description
Bring SimpleForm setup over to Sage along with necessary stubs to ensure this can be developed and tested in Sage.

## Related
TBD

**Comment by FuturaExtraBold** [comment]
@philschanely Taking this out of the Sage 3 Conversion milestone for the time-being. We need more documentation as to what the ask is here. This seems like a larger issue that will need several devs to accomplish.

**Comment by philschanely** [comment]
We may be able to now look at this under the proposed Patterns area and possibly also reflect it on the form control component examples.

**Comment by monkeypox8** [comment]
Moved to Jira: https://kajabi.atlassian.net/browse/UXD-60
