### ISSUE TITLE
Label

### ISSUE THREAD

**Issue by philschanely** [Kajabi/sage-lib#497]
## Description

Update component to match latest specs in Sage 3.0. Be sure to check the variations for this component and set up follow-up issues in Tier 4 as needed.

**Dependencies**:
- [Color updates](https://github.com/Kajabi/sage-lib/issues/490)
- [Border radius](https://github.com/Kajabi/sage-lib/issues/472)
- [Interactive states](https://github.com/Kajabi/sage-lib/issues/491)

**Links**
- [Figma specs](https://www.figma.com/file/9Km09NjlZHYWsMP7EGT8tI/WIP-Sage-3-%E2%80%94-Admin-Components?node-id=3655%3A16569)
- [Existing component/s](https://sage-design-system.kajabi.com/pages/component/label)

**Comment by FuturaExtraBold** [comment]
Closed in #584. Thanks, @QuintonJason!
