### ISSUE TITLE
Update Hero

### ISSUE THREAD

**Issue by philschanely** [Kajabi/sage-lib#510]
## Description

Update component to match latest specs in Sage 3.0. The following were noted during initial audit:

- Ensure two variations in size/spacing
- Ensure a fix for broken image paths on production

**Links**
- [Figma specs](https://www.figma.com/file/9Km09NjlZHYWsMP7EGT8tI/WIP-Sage-3-%E2%80%94-Admin-Components?node-id=3951%3A16301)
- [Existing component(s)](https://sage-design-system.kajabi.com/pages/component/hero)

**Comment by joedakroub** [comment]
Updated to support 2 sizes. Working on aspect ratios for the image between the 2 sizes. 95% done.

**Comment by FuturaExtraBold** [comment]
@joedakroub has plans to land this tomorrow, 9/14.
