### ISSUE TITLE
Update Pagination

### ISSUE THREAD

**Issue by philschanely** [Kajabi/sage-lib#514]
## Description

Update component to match latest specs in Sage 3.0. The following were noted during initial audit:

- Sync up interactive states
- Double-check border-radius colors and type specs

**Dependencies**:
- [Interactive states](https://github.com/Kajabi/sage-lib/issues/491)
- [Border radius](https://github.com/Kajabi/sage-lib/issues/472)

**Links**
- [Figma specs](https://www.figma.com/file/9Km09NjlZHYWsMP7EGT8tI/WIP-Sage-3-%E2%80%94-Admin-Components?node-id=3561%3A9796)
- [Existing component(s)](https://sage-design-system.kajabi.com/pages/component/pagination)

**Comment by pixelflips** [comment]
Fixed by #675
