### ISSUE TITLE
Update Toast

### ISSUE THREAD

**Issue by philschanely** [Kajabi/sage-lib#519]
## Description

Update component and subcomponents to match latest specs in Sage 3.0. The following were noted during initial audit:

- Revise colors and mapping
- Check spacing and icon sizes

**Dependencies**:
- [Color updates](https://github.com/Kajabi/sage-lib/issues/490)

**Links**
- [Figma specs](https://www.figma.com/file/9Km09NjlZHYWsMP7EGT8tI/WIP-Sage-3-%E2%80%94-Admin-Components?node-id=4483%3A18834)
- [Existing component(s)](https://sage-design-system.kajabi.com/pages/component/toast)

**Comment by pixelflips** [comment]
Fixed by #670
