### ISSUE TITLE
NEW: Upsell

### ISSUE THREAD

**Issue by philschanely** [Kajabi/sage-lib#525]
## Description

Add new component and subcomponents as needed per specs in Sage 3.0. See initial MVP build in `kajabi-products`

**Links**
- [Figma specs](https://www.figma.com/file/9Km09NjlZHYWsMP7EGT8tI/WIP-Sage-3-%E2%80%94-Admin-Components?node-id=3941%3A15462)

**Comment by FuturaExtraBold** [comment]
Removing this from the Sage 3 Conversion milestone, as this is a New component, not a conversion.

**Comment by philschanely** [comment]
@monicawheeler I agree this can be closed. If we need such a component it is probably best piloted in `kp` first.
