### ISSUE TITLE
Review Shadow tokens

### ISSUE THREAD

**Issue by philschanely** [Kajabi/sage-lib#528]
## Description

See specs below and align shadow tokens. Audit usage to align as appropriate.

[Figma Specs](https://www.figma.com/file/9Km09NjlZHYWsMP7EGT8tI/WIP-Sage-3-%E2%80%94-Admin-Components?node-id=3825%3A14741)

**Comment by QuintonJason** [comment]
Issue resolved in this PR: https://github.com/Kajabi/sage-lib/pull/571
