### ISSUE TITLE
Containers follow-up: `modal--large` width setting

### ISSUE THREAD

**Issue by philschanely** [Kajabi/sage-lib#572]
## Description

Prior to recent container conversion we had a `modal-lg` size that was set to `900px` and was retained manually in `_modal.scss`. This needs to be investigated to see if a) one of the new container sizes can be used instead for this setting or b) if a new container size is indeed needed for setting these large modals as desired.

## Related
#564 -- container conversion PR

**Comment by FuturaExtraBold** [comment]
@philschanely I'm assigning this task to you. The UX-Creation team talked about this. We've decided to either remove this from the Sage 3 Conversion milestone, or depend on you to complete this by the end of the cycle. It's your call.

**Comment by philschanely** [comment]
Moved to Jira https://kajabi.atlassian.net/browse/UXD-91
