### ISSUE TITLE
Tidy up deprecated aspects of Null View and Empty State

### ISSUE THREAD

**Issue by philschanely** [Kajabi/sage-lib#588]
## Description

Once Null View is removed from `kajabi-products` the following actions can be taken:

- Null View component and related files can be removed

Once Empty State usages of `text` and `compact` are refactored the following can happen:

- `compact` prop can be removed
- `component.content` output block can be simplified

## Related

- Sage prior Issue: #503 
- Blocking `kajabi-products` issue: #589

**Comment by philschanely** [comment]
@monkeypox8 flagging as a potential implementation task.

**Comment by monkeypox8** [comment]
Moved to Jira: https://kajabi.atlassian.net/browse/UXD-63
