### ISSUE TITLE
Refactor Null View and Empty State in `kajabi-products`

### ISSUE THREAD

**Issue by philschanely** [Kajabi/sage-lib#589]
## Description

Given recent work to consolidate Null View into Empty State, the following can be completed on uses of Null View in `kajabi-products:

- [ ] `SageNullView` should be replaced with `SageEmptyState`
- [ ] in such places add `scope: "page"`
- [ ] instances of `content_for :sage_null_view_actions` can be replaced with `content_for :sage_empty_state_actions`
- [ ] instances of `text: "<p>...</p>"` in SageNullView can be moved into `content_for :sage_empty_state_text` blocks instead.

Likewise a few things can be updated in uses of `SageEmptyState` as well:

- [ ] replace `compact: true` with `scope: "compact"`
- [ ] existing content blocks should more specifically implement `content_for :sage_empty_state_actions`

## Related

- Sage work #503 
- Sage cleanup after this #588
- [UXD-20](https://kajabi.atlassian.net/browse/UXD-20)

**Comment by philschanely** [comment]
@monkeypox8 Flagging this as a potential Implementation team task

**Comment by philschanely** [comment]
@monkeypox8 moving this over but it may actually be competed now?

**Comment by monkeypox8** [comment]
@pixelflips was able to audit usage and noted a few locations where the null state is still in play:
- admin/sites/<site_id>/contact_tags
- admin/sites/<site_id>/contacts
- admin/sites/<site_id>/email_campaigns
- admin/sites/<site_id>/events
- admin/sites/<site_id>/pipelines
- admin/sites/<site_id>/website_designs

Noting here also that image sizes are unoptimized. Worth a look once we do our update pass.

**Comment by monkeypox8** [comment]
Moved to Jira: https://kajabi.atlassian.net/browse/UXD-66
