### ISSUE TITLE
Add ability to set color for hint or Sage

### ISSUE THREAD

**Issue by darrellrivera** [Kajabi/sage-lib#612]
## Description
We were looking for a component that would be something like this: 
![Screen Shot 2021-07-06 at 1 41 51 PM](https://user-images.githubusercontent.com/1311769/124649394-71ab1500-de66-11eb-86ee-40209ef5f151.png)

It seemed like SageHint would be the closest we need, but we currently don't have the ability to set the color on that.  Would it be possible to add the same `color` property in SageAlert to SageHint?

**Comment by philschanely** [comment]
This does seem to be a strange mixture of Alert and Hint. I think we should get design's input on this first. But if they're ok with it we can def carry this concept forward.

**Comment by philschanely** [comment]
FWIW It appears the intent is to use Alert for this. We need to update this component to the latest spec [show here](https://www.figma.com/file/9Km09NjlZHYWsMP7EGT8tI/?node-id=6989%3A21570)

![image](https://user-images.githubusercontent.com/17955295/146224374-3d33c30e-e994-4db1-870e-194147583656.png)

**Comment by monicawheeler** [comment]
@darrellrivera - **[SageAlerts](https://sage-design-system.kajabi.com/pages/component/alert)/[Alert](https://sage-lib-storybook.herokuapp.com/?path=/docs/sage-alert--default)** now have a small variation. 

New issue has been created to account for new design work: https://github.com/Kajabi/sage-lib/issues/1105
