### ISSUE TITLE
Design: Naming and Evaluation of Sage Components

### ISSUE THREAD

**Issue by samcroswell** [Kajabi/sage-lib#628]
#### Naming

Review the list of components for more concise and/or clear names. List of some components to consider:

- Catalog item
- Collection item
- Content list
- Control list
- Dropdown
- Icon card

#### Evaluate

Review the list of components to determine if they are duplicative or if they can be combined into other components.

- Billboard
- Card highlight
- Chart legend
- Chart summary
- Copy text
- Data card
- Description
- Expandable card
- Feature toggle
- Indicator

**Comment by philschanely** [comment]
Similar to #819
