### ISSUE TITLE
Upsell modal

### ISSUE THREAD

**Issue by samcroswell** [Kajabi/sage-lib#630]
Just curious, does this need to be a full-on component in Sage, or should it be a Growth team-specific component that uses Sage atoms?

https://www.figma.com/file/9Km09NjlZHYWsMP7EGT8tI/%5BWIP%5D-Sage-3-%E2%80%94-Admin-Components?node-id=3435%3A15

**Comment by philschanely** [comment]
@samcroswell I can see a case either way. We do have a task #525 for building this new component and I believe we can put some structure in place for it that will help it being built consistently without making it too opinionated.

@FuturaExtraBold was starting work on this. Any thoughts?

CC: @monicawheeler @monkeypox8

**Comment by philschanely** [comment]
@samcroswell closing this issue as we've referenced these comments in #525
