### ISSUE TITLE
[Improvement] SageLink attributes configurations need a closer look

### ISSUE THREAD

**Issue by philschanely** [Kajabi/sage-lib#668]
## Description

SageLink renders a hyperlink anchor with sage styling and a few additional customizations such as showing a Help circle before or a Launch icon after. However, a few additional settings aimed to streamline common HTML attributes on these may not be fully applying as intended.

This PR requests an audit of the uses of SageLink in `kajabi-products` and how this element is being used, which properties are being taken advantage of, and how the component template could be improved to consistently apply all the desired aspects.

## Design

N/A

## Additional Information

N/A

**Comment by joedakroub** [comment]
`kajabi-products` has been updated to use `html_attributes`. The `attributes` property has been removed in the `SageLink` schema and all references in the docs updated.
