### ISSUE TITLE
[MediaTile] docs - add an example for a single `MediaTile`

### ISSUE THREAD

**Issue by QuintonJason** [Kajabi/sage-lib#693]
[MediaTile] docs - add an example for a single `MediaTile`

_Originally posted by @QuintonJason in https://github.com/Kajabi/sage-lib/issues/691#issuecomment-896039289_

**Comment by philschanely** [comment]
@QuintonJason for clarification on this are you looking for an example of MediaTile on its own rather than inside of `SageMediaTiles` loop?

**Comment by philschanely** [comment]
Assuming so I'll add a "Kitchen Sink" example of a standalone `MediaTile` on its own. LMK if this is not what you're wanting.
