### ISSUE TITLE
[a11y] skip-link design and development

### ISSUE THREAD

**Issue by monicawheeler** [Kajabi/sage-lib#700]
## Description

We need a skip-link both designed and implemented. Skip-links for the main navigation but also for views with lengthy secondary navigation menus

- [ ] discovery on how we can use existing patterns to create design for skip-link
 * Considerations: skip-link for main navigation but also internal navigations that are lengthy
- [ ] add skip-link to Sage
- [ ] implement skip-link in `kajabi-products`

## Design
None at this time. This may be a UXD-directed design effort.

## Additional Information

[CSS-Tricks Skipping to Content article](https://css-tricks.com/a-deep-dive-on-skipping-to-content)

**Comment by monkeypox8** [comment]
Moved to Jira board: https://kajabi.atlassian.net/browse/SAGE-111
