### ISSUE TITLE
[BUG] Button with loading state outputs truncated string/label

### ISSUE THREAD

**Issue by monkeypox8** [Kajabi/sage-lib#710]
## Detailed description

> Describe in detail the issue you're having.

Examples for the Sage button loading indicator are not displaying the full text provided for the `aria-label` replacement.

> Is this issue related to a specific component?

Sage buttons with `spinner_on_submit` enabled

> What did you expect to happen? What happened instead? What would you like to see changed?

The string provided for `data-js-sage-spinner-on-submit` is breaking out of the attribute bounds. Could be an unescaped character or an extra quote closing the property value prematurely.

> What browser are you working in?

All browsers are affected, though each appears to render the string differently.

## Steps to reproduce
Describe the steps to reproduce the behavior: 
1. View the [Sage Button page](https://sage-design-system.kajabi.com/pages/component/button#) and scroll to the "Loading State" example
2. Inspect the button, and verify that the attribute `data-js-sage-spinner-on-submit` does not display the full example string "My aria label" as expected
3. Click the button and confirm that the button's `aria-label` also does not display the full text string

## Screenshots
|  Browser | Inactive state   |  Active state  |
|--------|------|--|
|Safari|![safari-inactive](https://user-images.githubusercontent.com/816579/129284065-bd47f6f0-3248-4f1e-8973-52b2ed585454.png)|![safari-active](https://user-images.githubusercontent.com/816579/129284072-674f10e8-b03e-4bf2-b254-ec72cdfdd62f.png)|
|Chrome|![chrome](https://user-images.githubusercontent.com/816579/129284085-a42122b5-4b41-49c9-aa15-c47e9221424f.png)|![chrome-active](https://user-images.githubusercontent.com/816579/129284097-fee63e21-26fe-4ce8-b9e5-9878a50a7d9d.png)|
|Firefox|![ff-inactive](https://user-images.githubusercontent.com/816579/129284111-b1bc1db9-19a0-4807-83fa-7977bc887f4b.png)|![ff-active](https://user-images.githubusercontent.com/816579/129284115-7bb8440c-a9e8-41bc-afb4-236b788c119e.png)|

**Comment by philschanely** [comment]
Duped in Jira for record-keeping https://kajabi.atlassian.net/browse/UXD-84
