### ISSUE TITLE
[Improvement] SPIKE: Look at integrating Percy

### ISSUE THREAD

**Issue by monicawheeler** [Kajabi/sage-lib#724]
## Description

In an effort to improve automation for visual changes, this issue is for investigating the use of Percy for automated visual regression testing 🙌

## Resources
[Percy site](https://percy.io/)
[Percy docs](https://docs.percy.io/docs/github)

**Comment by philschanely** [comment]
Moved to Jira https://kajabi.atlassian.net/browse/UXD-76
