### ISSUE TITLE
[Enhancement] DISCOVERY - Intellisense for Sage components

### ISSUE THREAD

**Issue by monicawheeler** [Kajabi/sage-lib#728]
## Description

To better serve developers, look at options for adding Intellisense for Sage components. 
* [Slack discussion around this feature](https://kajabi.slack.com/archives/CU5JG6N2E/p1627061070395800)

As a stop-gap, VSCode snippets could provide a ton of value if rolling out Intellisense is a large effort. 

## Resources

To reference creating an extension in VSCode, see article here: [VSCode First Extension](https://code.visualstudio.com/api/get-started/your-first-extension)

To reference how Tailwind implements their Intellisense, see repo: [Tailwind CSS's GitHub Intellisense repo](https://github.com/tailwindlabs/tailwindcss-intellisense)

To reference the snippets Gist @monkeypox8 created, see Gist: [Kevin's Snippet Gist](https://gist.github.com/monkeypox8/223558518c1ec47e0e3e0ce12296d7f3)

**Comment by philschanely** [comment]
Moved to Jira https://kajabi.atlassian.net/browse/UXD-74
