### ISSUE TITLE
[BUG] Marking an input as disabled and not required is hiding the label

### ISSUE THREAD

**Issue by darrellrivera** [Kajabi/sage-lib#731]
## Detailed description
I have [this PR](https://github.com/Kajabi/kajabi-products/pull/20356/files) where we marked some input fields as disabled; however, when I do that, it was also hiding the label (screenshot can be found in discussion [here](https://github.com/Kajabi/kajabi-products/pull/20356#discussion_r691653268)).  I was using chrome when I noticed this issue (for now I added css to show the label again)

## Steps to reproduce
Describe the steps to reproduce the behavior: 
1. Mark a text input as disabled and the lable does not appear

## Screenshots
See discussion [here](https://github.com/Kajabi/kajabi-products/pull/20356#discussion_r691653268)

**Comment by philschanely** [comment]
Moved to Jira https://kajabi.atlassian.net/browse/UXD-62
