### ISSUE TITLE
[Improvement] Investigate Codepen/JSFiddle integration in Sage docs site

### ISSUE THREAD

**Issue by monkeypox8** [Kajabi/sage-lib#735]
## Description
In order to help developers quickly spin up experiments, we should look into the addition of a code sandbox tool. This could mean embedding or linking to predefined environments in the Sage documentation.

Storybook already handles the majority of this functionality on the React side, but we do not have an equivalent with Rails/HTML.

**Questions**
- [ ] How can we ensure that sandboxes are linking to the most recent releases of Sage?
- [ ] Do we want to/have to include the entire Sage release package with external links?

## Additional Information
- https://blog.codepen.io/documentation/prefill/
- https://codepen.io/mercuryworks/pen/EyQaBO

**Comment by philschanely** [comment]
Moved to Jira https://kajabi.atlassian.net/browse/UXD-73
