### ISSUE TITLE
[Improvement] Include an option for `expanded` in Expandable Card component

### ISSUE THREAD

**Issue by monicawheeler** [Kajabi/sage-lib#759]
## Description

Currently, the expandable card component defaults to a closed or inactive state. It would be helpful to have an option to load the component in an active state where the card is expanded rather closed.

## Design
[Figma](https://www.figma.com/file/9Km09NjlZHYWsMP7EGT8tI/%5BWIP%5D-Sage-3-%E2%80%94-Admin-Components?node-id=6999%3A23010)
[Sage docs](http://sage-design-system.kajabi.com/pages/component/expandable_card)

## Additional Information
[Slack thread for additional context](https://kajabi.slack.com/archives/C02ASAATRQA/p1630505577002200)

**Comment by AndrwM** [comment]
Where this `active` option would be added in the Coaching Product:

https://github.com/Kajabi/kajabi-products/pull/20528/files#diff-43a581bbcd0381a42b851086c671e6dd2a545d86cb7e8cf557ba212aa7c0f35d

```
https://www.kajabi.test:3000/admin/coaching_programs/:progam_id/clients/:client_id
```

**Comment by monicawheeler** [comment]
@AndrwM - FYI - I started the work on this this week but won't be back in the office until Sept 15. Please move forward with your temporary solution and we will get this implemented when I return. Thank you for your patience!
