### ISSUE TITLE
[Improvement] Dynamic Select documentation improvements

### ISSUE THREAD

**Issue by monicawheeler** [Kajabi/sage-lib#761]
## Description

- [ ] - Address several spelling and grammar errors.
- [ ] - Include a more descriptive description
- [ ] - Provide a live example if possible

## Designs
_need design files_

## Additional Information

![Screen Shot 2021-09-01 at 10 15 07 AM](https://user-images.githubusercontent.com/24237393/131698001-5143604c-6617-4601-8939-683a7e099568.png)

**Comment by monkeypox8** [comment]
Moved to Jira: https://kajabi.atlassian.net/browse/UXD-104
