### ISSUE TITLE
[Improvement] Styling issue for new site theme install modal

### ISSUE THREAD

**Issue by ForrestHolt** [Kajabi/sage-lib#774]
## Description
Styling issue for new site theme install modal:
<img width="1563" alt="131716495-d2bbe39f-a4f6-40d2-b96d-157f89dc8704" src="https://user-images.githubusercontent.com/17749903/131736472-23758bc3-93b0-47a3-8bb6-bca83d3fbf2e.png">

You can get this modal by hitting the /admin/sites/{site_id}/themes/pick page and clicking on a theme tile

## Design
How it should be looking: 
<img width="1650" alt="Screen Shot 2021-09-01 at 1 02 11 PM" src="https://user-images.githubusercontent.com/17749903/131736429-9c193d49-2eda-4ae9-b9e1-afa242084a57.png">

## Additional Information
Issue came up via https://github.com/Kajabi/kajabi-products/pull/20535 and was instructed to file this follow up

**Comment by ForrestHolt** [comment]
Hey @FuturaExtraBold @anechol ! Any idea when this could one be resolved?

**Comment by philschanely** [comment]
@ForrestHolt did we ever resolve this? 😳

**Comment by ForrestHolt** [comment]
@philschanely Yes we did, Jamell took care of it. I will close this one 😎
