### ISSUE TITLE
[Improvement] Provide a responsive image solution

### ISSUE THREAD

**Issue by monicawheeler** [Kajabi/sage-lib#776]
## Description

Look at how we handle responsive images and provide a clear solution for developers to implement

## Example
![responsive-image](https://user-images.githubusercontent.com/24237393/131863020-68dfbf27-3713-4cd3-a735-9bd1496ed947.gif)

## Additional Information
[Slack thread](https://kajabi.slack.com/archives/C02ASAATRQA/p1630541830023000?thread_ts=1630535548.021600&cid=C02ASAATRQA)

**Comment by monkeypox8** [comment]
Moved to Jira: https://kajabi.atlassian.net/browse/SAGE-106
