### ISSUE TITLE
[Improvement] update Menu item (Dropdown item) to accommodate designs for Coaching

### ISSUE THREAD

**Issue by monicawheeler** [Kajabi/sage-lib#777]
## Description

Add an option for Menus (dropdowns) that line up with designs for Coaching

## Design
[Coaching usecase](https://www.figma.com/file/zTHwmRx2GpM1Omq2HYbfdb/Coaching-%2F-Create-%26-Manage?node-id=5934%3A68545)

[Applicable Figma reference - does not include this variation](https://www.figma.com/file/9Km09NjlZHYWsMP7EGT8tI/%5BWIP%5D-Sage-3-%E2%80%94-Admin-Components?node-id=3671%3A16721)

### Screenshots
![Screen Shot 2021-08-24 at 12 41 37 PM](https://user-images.githubusercontent.com/24237393/131873638-9d15d643-60bd-43df-b804-ccf5aa3318d8.png)

**Comment by philschanely** [comment]
These look nice! Here I see a lot of similarity again with existing components. In case its helpful:

- We have a dot effect like this in the recent updates to StatBox with `legend_dot`. Are these sizes and color options the same? If not, should they be? Should this be a new component we can drop into layouts (kind of like icons?) with some props for adding/enforcing necessary a11y features?
- If this has same interactive effects as standard dropdown items, perhaps we can consider a way to open up dropdown items to take a custom inner content (if they don't already?)

Once again it seems that some effort to reconcile this variation on dropdown items with the main library of Sage things would be beneficial before we build it out.

**Comment by monicawheeler** [comment]
Spoke with @QuintonJason and we will work on constructing a collection of components for this use case, within `kajabi-products` rather than a custom component or update to an existing component in `sage-lib`. Closing for now. 
Relevant ticket for BUILD: https://kajabi.atlassian.net/browse/BUILD-1623
