### ISSUE TITLE
[Improvement] New Catalog Item option

### ISSUE THREAD

**Issue by monicawheeler** [Kajabi/sage-lib#778]
## Description
Add an option for Catalog Item that line up with designs for Coaching

## Design
[Coaching usecase](https://www.figma.com/file/zTHwmRx2GpM1Omq2HYbfdb/Coaching-%2F-Create-%26-Manage?node-id=5934%3A69599)
[Applicable Figma reference - does not include this variation](https://www.figma.com/file/9Km09NjlZHYWsMP7EGT8tI/%5BWIP%5D-Sage-3-%E2%80%94-Admin-Components?node-id=6999%3A21759)

### Screenshot
![Screen Shot 2021-08-24 at 12 42 05 PM](https://user-images.githubusercontent.com/24237393/131874469-c48c9d04-a284-4884-b479-713e3b18b1fa.png)

**Comment by philschanely** [comment]
Exciting mockup here! This also seems to deserve some further conversation:

First, is this an opportunity to pilot a process whereby we get the designed thing to be reconciled or spec'd out in the official Sage Figma file before charging forward? If not, I'd suggest we build this in `kp` first and move/update it once it is spec'd out. 

Either way, it looks like many if not all the aspects here may already be possible using existing components and may not need to be a pure new sage component. For example, this gets pretty close:

```erb
SagePanelList
  SagePanelListItem grid_template: eme
    SageAvatar
    SagePanelBlock or Stack
      (name)
      (meta as SageProperty's)
    SagePanelBlock or Stack
      (session name)
      (meta)
    SageButton/SageLink with internal icon (would the link also wrap around whole row with pseudo-trick?)
```

Some questions to consider:

- *What do we want this to do responsively?* If the default setup for the Grid Templates leads to an undesirable responsive solution then a custom component may be justified—or possibly even some local responsive grid settings through like a custom grid template. _Side note: we may benefit from thinking more about this notion of custom grid templates: how to add them to a component, where to add the styles, etc._
- *Should the whole row be clickable?* If so, it may be worth just looking at a modifier on Sage Link or Sage Button that allows for something other than the Link or Button to be `position; relative` and thus allow the focus ring, etc. to bubble out broader; or something like that...
- If this is indeed a new catalog item variation that we need to build into Sage...
  - *How do we distinguish it from others and prescribe its intended uses?* 
  - *How open versus closed should it be for other uses?*

Another consideration might be to open up catalog item for custom grid templates such as this one and to add a "link" affordance for the right side and related interactive features. This might be a good middle ground that would make catalog item open for custom internal layouts while affording a consistent frame for context.

**Comment by QuintonJason** [comment]
We're currently not implementing this in `sage-lib`. This has been added to `kajabi-products` in [this PR](https://github.com/Kajabi/kajabi-products/pull/20602)
