### ISSUE TITLE
[Suggestion] SageHeading and SageText components

### ISSUE THREAD

**Issue by joedakroub** [Kajabi/sage-lib#782]
## Description
It would be desirable to have a `SageHeading` and `SageText` set of components that encapsulate the the common things we currently do within Kajabi Products to style text. This would help remove custom HTML within the app but also alleviate common mistakes when marking up headlines/text and reduce the usage of specific Sage classes when using text.

One possible configuration:

**SageHeading**
- `level` - [1, 2, 3, 4, 5, 6]
- `spec` - heading-1, heading-2, heading-3, heading-4, heading-5, heading-6

**SageText**
- `tag` - [p, span, em, strong, none]
- `spec` - body, body-small, body-xsmall, body-med, body-semi, body-bold, body-xsmall-med, body-xsmall-semi, body-xsmall-bold

**Comment by philschanely** [comment]
We inadvertently duped this with #943
