### ISSUE TITLE
[Improvement] Document component-level attributes

### ISSUE THREAD

**Issue by monkeypox8** [Kajabi/sage-lib#790]
## Description
It would be helpful to have general documentation for **all** base-level attributes available on any `sage_component`. This could be similar to the [spacing](https://sage-design-system.kajabi.com/pages/helpers/spacing) page on the docs site.

`test_id`
`html_attributes`
~~`spacer`~~
`css_classes`

These attributes have been added for some components individually, but it's not immediately noticeable that all components can take advantage.

**Comment by philschanely** [comment]
MOved to Jira https://kajabi.atlassian.net/browse/UXD-79
