### ISSUE TITLE
[BUG] SageFormInput prefix & suffix don't support strings with spaces

### ISSUE THREAD

**Issue by pixelflips** [Kajabi/sage-lib#792]
## Detailed description

> Describe in detail the issue you're having.

When adding a prefix or suffix where the string contains a space (e.g. two words), the form input component misplaces the string for the data attribute and the label does not display any additional words after a space.

> Is this issue related to a specific component?

SageFormInput

> What did you expect to happen? What happened instead? What would you like to see changed?

Expect prefix or suffix to display full string.

> What browser are you working in?

Chrome / Firefox

## Steps to reproduce
Describe the steps to reproduce the behavior: 

1. Spin up docs site
2. Visit http://localhost:4000/pages/component/form_input
3. Update prefix or suffix for an input with two words in `docs/app/views/examples/components/form_input/_preview.html.erb`
4. Notice that the prefix or suffix ignores words after space.

## Screenshots
For the provided screenshot the prefix and suffix strings were set to "two words" 

![Screen Shot 2021-09-13 at 4 03 18 PM](https://user-images.githubusercontent.com/1175111/133168223-0e8bca6a-09fb-4b81-8486-d2e6cdecee80.png)

**Comment by monkeypox8** [comment]
Moved to Jira: https://kajabi.atlassian.net/browse/UXD-72
