### ISSUE TITLE
Icon List --> Control List

### ISSUE THREAD

**Issue by FuturaExtraBold** [Kajabi/sage-lib#808]
## Description
Icon List will need to become Control List. This will deprecate Icon List. All instances in `kajabi-products` will need to be updated. This is a follow-up of the Icon List visual updates as part of the Sage 3 conversion.

**Dependencies**:
- Follow-up to #501 

**Links**
- [Figma specs](https://www.figma.com/file/9Km09NjlZHYWsMP7EGT8tI/WIP-Sage-3-%E2%80%94-Admin-Components?node-id=3655%3A22427)
- [Existing component(s)](https://sage-design-system.kajabi.com/pages/component/icon_list)

**Comment by monkeypox8** [comment]
Moved to Jira: https://kajabi.atlassian.net/browse/SAGE-107
