### ISSUE TITLE
[BUG] Sage docs showing wrong version in header

### ISSUE THREAD

**Issue by monicawheeler** [Kajabi/sage-lib#822]
## Detailed description

In the header of the Sage docs, the release version is incorrect

## Steps to reproduce

1. Navigate to http://localhost:4000/pages/component/alert
2. View the version is 4.11.1 but it should be 4.17.0

## Screenshots
![Screen Shot 2021-09-22 at 2 06 18 PM](https://user-images.githubusercontent.com/24237393/134406370-51e56419-ad8b-4e9d-b00b-e9ba359eaac8.png)

**Comment by monicawheeler** [comment]
Context: https://kajabi.slack.com/archives/CU5JG6N2E/p1607703197067200
> Yeah so just so everyone totally understands that flow:
https://github.com/Kajabi/sage-lib/blob/master/docs/package.json
The main docs folder is the gem + an npm package that's hooked into Lerna. The way the gem gets bumped is the process script will look to see what Lerna bumped the package too and then bump the gem to match it. e.g. the Version of that package.json file should always match whats in the version.rb file

**Comment by monicawheeler** [comment]
Commit that last updated the version:
https://github.com/Kajabi/sage-lib/commit/9a18a2966e187bef4fdb660da4d60916b78fdb27

**Comment by monicawheeler** [comment]
`/bin/bump-gem.sh` is where the bump happens

**Comment by monicawheeler** [comment]
Within in the `release-deploy.yml` during the "Lerna Publish" step, the command `yarn version` is supposed to run, but currently is not running.

**Comment by monicawheeler** [comment]
Seems to be related: https://github.com/lerna/lerna/issues/2753

**Comment by voodooGQ** [comment]
https://github.com/Kajabi/sage-lib/blob/develop/.github/workflows/release-deploy.yml#L75 I think we may need to add a `sudo` declaration here. Did a bunch of reading and kept finding references to `npm --unsafe-perm`. Since we're using `yarn` we don't have the option to pass `unsafe-perm` through the cli, however, it seems that the on-running conversation suggests that the script loses permissions for running secondary scripts along the way.

**Comment by monicawheeler** [comment]
@voodooGQ - so the line to run would be:

`sudo run: npx lerna publish --registry github --yes`

Correct?

**Comment by voodooGQ** [comment]
`run: sudo npx lerna publish --registry github --yes`*

**Comment by FuturaExtraBold** [comment]
Nice catch, Monica!
