### ISSUE TITLE
Automating URL Types

### ISSUE THREAD

**Issue by FuturaExtraBold** [Kajabi/sage-lib#826]
## Description
Look into automating `url` types, esp. with `domain-slug` (prefix) versus `subdomain` (suffix)

## Additional Information
This is a follow-up from #505. The visual changes were made as a part of the Sage 3 conversion milestone. This issue is for  the outstanding logic updates.

**Comment by philschanely** [comment]
Moved to Jira https://kajabi.atlassian.net/browse/UXD-98
