### ISSUE TITLE
[Improvement] Tooltip and Popover Responsive updates

### ISSUE THREAD

**Issue by QuintonJason** [Kajabi/sage-lib#827]
### Status: **blocking**
On smaller screens the tooltips see to be revisited as they aren't optimized for mobile. We lose some of our flexibility with positioning, especially `left` and `right`. We'll need a mobile design that will guide patterns when content is hidden and shown. The designs will need to be updated to include the trigger that the tooltip or popover is positioned in reference to.

## Design

- [Tooltips](https://www.figma.com/file/9Km09NjlZHYWsMP7EGT8tI/Sage-3-for-Admin?node-id=6999%3A23154)
- [Popovers](https://www.figma.com/file/9Km09NjlZHYWsMP7EGT8tI/Sage-3-for-Admin?node-id=6999%3A23138)

## Additional Information

<img width="476" alt="Screen Shot 2021-09-20 at 11 44 35 AM" src="https://user-images.githubusercontent.com/1241836/134564779-1f3545e8-40fc-4ce3-a415-b1ed418a2987.png">

**Comment by philschanely** [comment]
Moved to Jira https://kajabi.atlassian.net/browse/UXD-96
