### ISSUE TITLE
[Improvement] Improve mobile navigation

### ISSUE THREAD

**Issue by QuintonJason** [Kajabi/sage-lib#828]
## Description

Trying to navigate on mobile was challenging for me and this ticket is the result. Two main points I was trying to work through:
1. When on the home page, not sure which one to click on because there aren't any words and the iconography alone isn't enough to correlate the correct page
2. When on sub nav page and interact with the sidebar, if there's a need to get to another top level page I must repeat the number button point

## Additional Information
![Screen Shot 2021-09-23 at 1 29 22 PM](https://user-images.githubusercontent.com/1241836/134570963-1c357c92-1926-4a16-9eb2-f9fab4ece0c0.png)

**Comment by anechol** [comment]
Poking around with this, there's some things to consider/questions to ask:
1. What direction should we pursue for these items? (Do we need design help?)
    - A second nav menu seems like bad practice, or at least very uncommon.
    - Allowing the navbar to scroll horizontally. Possible, but requires some visual indication that scrolling is possible.
    - Hiding overflowing nav items under a "More" menu/dropdown
2. We should consider trapping focus within the sidebar when it's open. Currently, opening the menu with the keyboard still allows you to scroll through the entire site.

**Comment by philschanely** [comment]
Moved to Jira https://kajabi.atlassian.net/browse/UXD-97
