### ISSUE TITLE
[Improvement] Sage 3 - Tooltip Deprecations and Updates

### ISSUE THREAD

**Issue by anechol** [Kajabi/sage-lib#835]
## Description

The Tooltip component updates for Sage 3 call for a deprecation to the following props:
- `size`
- `theme`

The aim is to establish a proper protocol/process for safely deprecating props within Sage components to minimize negative impact on Kajabi Products.

Additionally, there is a further update for pointer positioning on top- and bottom-positioned tooltips seen in the image below.

## Design

[Figma](https://www.figma.com/file/9Km09NjlZHYWsMP7EGT8tI/Sage-3-for-Admin?node-id=4533%3A142)

## Additional Information

<img width="1285" alt="Screen Shot 2021-09-27 at 4 22 21 PM" src="https://user-images.githubusercontent.com/14791307/134987354-b0f83a6c-fb50-4458-96da-cd85381a69d7.png">

#834 - Initial Sage 3 styling updates addressed here.

**Comment by monkeypox8** [comment]
Moved to Jira: https://kajabi.atlassian.net/browse/UXD-99
