### ISSUE TITLE
[Improvement] a11y - add an Accessibility section within doc site

### ISSUE THREAD

**Issue by monicawheeler** [Kajabi/sage-lib#836]
## Description
Add a feature within the documentation site that highlights our Accessibility compliance.

## Design
Pluralsight has a section that shows the results of a11y tests and audits

### Screenshot
![Screen Shot 2021-09-28 at 8 54 31 AM](https://user-images.githubusercontent.com/24237393/135101466-6fd4262a-57d4-45a2-a6de-6c0861bd014c.png)

### Link
https://design-system.pluralsight.com/components/note

**Comment by philschanely** [comment]
Not opposed to this but I think we should consider:
- is this automated or manual?
- how do we continue to maintain once implemented?
- is this relevant to our primary stakeholders that it should merit a spot on each component versus a standalone page summarizing all components separately?

**Comment by monkeypox8** [comment]
Moved to Jira: https://kajabi.atlassian.net/browse/UXD-101
