### ISSUE TITLE
[Improvement] Alert: close button relying on class instead of attribute

### ISSUE THREAD

**Issue by QuintonJason** [Kajabi/sage-lib#842]
## Description

Currently the Alert close button is relying on all occurrences of`.sage-alert__close` instead of a data attribute. In some cases the close button will reside in the `.sage-alert__actions` in the form of some confirmation text.

Recommendation: 
Change the selector from `.sage-alert__close` -> `[data-js-alert--close]`

## Design

![Screen Shot 2021-09-29 at 2 46 39 PM](https://user-images.githubusercontent.com/1241836/135338338-a8cd39ed-db59-4de1-b9d2-d669d6ee9a42.png)

**Comment by monkeypox8** [comment]
Moved to Jira: https://kajabi.atlassian.net/browse/UXD-102
