### ISSUE TITLE
[Improvement] Sage 3 - Copy Button Functionality Updates

### ISSUE THREAD

**Issue by anechol** [Kajabi/sage-lib#845]
## Description

The Copy Button component calls for the following additions for Sage 3:
- New variation of input/value field with a floating label
- Updated JS settings to account for prefixes, suffixes, and concatenation

## Design

[Figma](https://www.figma.com/file/9Km09NjlZHYWsMP7EGT8tI/Sage-3-for-Admin?node-id=4195%3A20283)

## Additional Information

#520 - Original Sage 3 issue
#843 - Initial Sage 3 styling updates addressed here.

**Comment by monkeypox8** [comment]
Moved to Jira: https://kajabi.atlassian.net/browse/UXD-103
