### ISSUE TITLE
[Improvement] README's - update the README's for all of the packages

### ISSUE THREAD

**Issue by monicawheeler** [Kajabi/sage-lib#872]
## Description

The README's for each **[package](https://github.com/Kajabi/sage-lib/tree/develop/packages)** needs documentation attention.

For each package, consider covering the following in plain, easy to understand language:
* What the project does
* Why the project is useful
* How users can get started with the project
* Where users can get help with the project
* Who maintains and contributes to the project

Also, consider keeping the README's consistent in their headings as to make it a unifying experience between each one.

## Additional Information

| Package | Current View | Link |
| ----------- | ----------- | ----------- |
| `sage-assets` | ![Screen Shot 2021-10-08 at 10 57 52 AM](https://user-images.githubusercontent.com/24237393/136587621-6b15edcb-b55f-4b98-8a3a-fc13267fa2ea.png) | https://github.com/Kajabi/sage-lib/tree/develop/packages/sage-assets |
| `sage-packs` | ![Screen Shot 2021-10-08 at 10 58 31 AM](https://user-images.githubusercontent.com/24237393/136587721-a291243a-f0d3-4e69-9417-c7268d168dc5.png) | https://github.com/Kajabi/sage-lib/tree/develop/packages/sage-packs |
| `sage-react` | ![Screen Shot 2021-10-08 at 10 59 01 AM](https://user-images.githubusercontent.com/24237393/136587803-84690f4a-efae-405b-9dc5-65c41f3ea017.png)  | https://github.com/Kajabi/sage-lib/tree/develop/packages/sage-react |
| `sage-system` |  ![Screen Shot 2021-10-08 at 10 59 25 AM](https://user-images.githubusercontent.com/24237393/136587851-65adfed9-0065-4e0f-aeb5-f4741a4ab2a6.png) | https://github.com/Kajabi/sage-lib/tree/develop/packages/sage-system |

**Comment by philschanely** [comment]
MOved to Jira https://kajabi.atlassian.net/browse/UXD-75
