### ISSUE TITLE
[Enhancement] Avatar: Add badge property

### ISSUE THREAD

**Issue by monicawheeler** [Kajabi/sage-lib#881]
- [x] ~~**BLOCKER: Need Design to integrate in Figma Specs for SSoT**~~ [Badge spec](https://www.figma.com/file/9Km09NjlZHYWsMP7EGT8tI/?node-id=6989%3A21606) is added in Figma.
  - [x] Should consider how badge scales and adjusts placement at different avatar sizes
  - [x] ~~Are any other badges likely (red with ! for example?)~~
- [ ] - Avatar badge
    - [ ] Sizes -- specs shows when to switch between various icon sizes. So the icon size should be automated based on the avatar size provided and not require the user to specify the icon size but only the avatar size as they currently do.
    - [ ] Colors -- note the blue icon color but also the "check" is white so may suggest we lay a background color behind the icon in some fashion.
    - [ ] Icon -- here we should cement in the `check-circle` icon for now as we have no expectation of a different badge in the future. However, if this is open for easy adjustment later when that case does arise that would be forward-thinking 👍 
    - [ ] Placement in lower right as shown in specs.

## Design

[Avatar Spec](https://www.figma.com/file/9Km09NjlZHYWsMP7EGT8tI/?node-id=6989%3A21606)

![image](https://user-images.githubusercontent.com/17955295/141002782-af84b620-ee6d-43b8-b4c4-c8651c96b314.png)

[Contextual Use](https://www.figma.com/proto/NQnIQAPgiLb6gQzNNGJidH/Contact-Profile?page-id=1197%3A19743&node-id=1830%3A41361&viewport=437%2C48%2C0.32&scaling=min-zoom&starting-point-node-id=1830%3A41361&show-proto-sidebar=1)

![Screen Shot 2021-10-13 at 9 19 57 AM](https://user-images.githubusercontent.com/24237393/137151802-0f6bb259-b320-458e-b7cc-e152d231dee0.png)
t

**Comment by philschanely** [comment]
FYI @anechol the avatar spec is now updated with what is needed to accomplish this ticket.

CC: @monicawheeler

**Comment by anechol** [comment]
Thanks for the update!
