### ISSUE TITLE
[Enhancement] Icon: New icons for contact profile

### ISSUE THREAD

**Issue by philschanely** [Kajabi/sage-lib#884]
- [x] **BLOCKER: Need icon font export from Design.** Contact @xtinesun for status. #915 
- [ ] Need at least the following added to icon library:
  - [ ] ![image](https://user-images.githubusercontent.com/17955295/137333168-510664cc-a14f-4a65-af5e-526cfc091338.png) expand
  - [ ] ![image](https://user-images.githubusercontent.com/17955295/137333211-a7a7d6a0-7cff-47b4-aee2-18c9a986577f.png) reset password
  - [ ] ![image](https://user-images.githubusercontent.com/17955295/137333243-25f933e7-84da-47bb-9ebe-69edf8b20035.png) grant offer
  - [ ] ![image](https://user-images.githubusercontent.com/17955295/137972050-e2217f2e-2df6-450b-b80f-e9fa2ca0e81f.png)

## In design
![Screen Shot 2021-10-18 at 9 57 14 AM](https://user-images.githubusercontent.com/24237393/137756619-f775d7d8-65f2-4a34-9f9e-bd191d093561.png)

**Comment by monicawheeler** [comment]
Request sent to Design: https://kajabi.slack.com/archives/C01A424HY8Y/p1634569150073600

**Comment by philschanely** [comment]
Note: reset password was accidentally ommitted from this PR but will be in [the next one](https://github.com/Kajabi/sage-lib/issues/973)
