### ISSUE TITLE
[Enhancement] Button: Document "copy" functionality and example

### ISSUE THREAD

**Issue by philschanely** [Kajabi/sage-lib#890]
Common use of standard button is to use it to copy a static value; this needs to be shown on Button page.

See Copy Button component, which is currently set up more for form field contexts. It nonetheless uses the `data-js-copybutton` property that can be put on other components.

- [ ] Add a preview/documentation example of using this attribute on a standard button such as to achieve the contextual use shown in the mock below.

![Screen Shot 2021-10-14 at 10 42 10 AM](https://user-images.githubusercontent.com/17955295/137340507-c733b081-89a2-40d5-adec-6b5bc90e59cb.png)

Note that in this mock it is acceptable and possible for the Button to be just the icon-only or also encompass the email value. Regardless, the `data-js-...` attribute can be implemented. Both variations may be useful to demonstrate.

**Comment by anechol** [comment]
Closing this as a borderless variation of the Copy Button has been added to Sage.
