### ISSUE TITLE
[Improvement] Sage Modal Scrolling

### ISSUE THREAD

**Issue by anechol** [Kajabi/sage-lib#897]
## Description

Per closed ticket #531, there's a design request to consider scrolling within Sage Modals to prevent modal from being scrolled below the fold on mobile devices.

### Previous Solution + Further Considerations
A PR was filled out to resolve this issue, #851. A follow-up PR (#868) was created to address a minor bug in Windows. Ultimately PR #868 reverted the modal scrolling as there was an additional bug found and documented in #870:

<img width="662" alt="Screen Shot 2021-10-08 at 9 31 20 AM" src="https://user-images.githubusercontent.com/14791307/137525731-09e64c45-73f7-4686-8c1c-a125f054a931.png">

Given the documented bug, there are some considerations for implementing this update in the future:

- Unintended usage of raw Sage classes over Sage components
- Third-party CSS/styling that cannot be predicted within the context of Sage CSS.

Previous solution:
- Give `max-height` to modal container
- Give `overflow-x: hidden` and `overflow-y: auto` to modal container

## Design

N/A

## Additional Information
References:
- #531 - Initial issue request
- #851 - PR addressing above issue
- #860 - Initial Windows bug issue
- #868 - PR that reverted scrolling update

**Comment by philschanely** [comment]
Moved to Jira https://kajabi.atlassian.net/browse/UXD-95
