### ISSUE TITLE
[Improvement] Update PR template to align with clearer priority labels

### ISSUE THREAD

**Issue by monicawheeler** [Kajabi/sage-lib#910]
## Description

Priority labels in PRs are not clear enough. Update the PR template to provide clearer and concise instructions so it's easy to use the correct priority label. 

## Template location
https://github.com/Kajabi/sage-lib/blob/develop/.github/pull_request_template.md

## Additional Information
Handbook update issue: kajabi/UXD-Handbook#38

**Comment by philschanely** [comment]
Closing as we move to Jira.
