### ISSUE TITLE
[Suggestion] Table - ascending/descending sort table on table cell header arrow click

### ISSUE THREAD

**Issue by QuintonJason** [Kajabi/sage-lib#922]
## Description

-  [ ] clicking the table header cell's arrow should toggle between sorting the rows in ascending or descending order. the arrow would reposition appropriately for user feedback
<img width="1107" alt="Screen_Shot_2021-10-21_at_12_56_30_PM" src="https://user-images.githubusercontent.com/1241836/138331829-179cb9b7-c7fb-44ed-b60e-f5ab1f4fe062.png">

**Comment by philschanely** [comment]
Moved to Jira https://kajabi.atlassian.net/browse/UXD-80
