### ISSUE TITLE
[Suggestion] Map Storybook Link in Rails to Correct Environment

### ISSUE THREAD

**Issue by anechol** [Kajabi/sage-lib#929]
## Description

Currently, the React Storybook component links on the Rails side of the app are all linking to the production site, even while working on the local project. If not paying close attention, it can be confusing as it appears that changes being made are not reflected in React when it's really just the wrong environment.

**Comment by philschanely** [comment]
Moved to Jira https://kajabi.atlassian.net/browse/UXD-77
