### ISSUE TITLE
[Suggestion] Update Docs to Reflect Required Props

### ISSUE THREAD

**Issue by anechol** [Kajabi/sage-lib#932]
## Description

Currently, the vast majority of components lack any indication of which props are required for the component to be rendered properly. It would be helpful for developers to know exactly which props they need at a bare minimum for the components they use.

- [ ] Add a visual indicator (TBD) next to required props in Rails documentation
- [ ] Audit all components to ensure this flag is present for required props

**Comment by monkeypox8** [comment]
Moved to Jira: https://kajabi.atlassian.net/browse/UXD-85
